site_name: senchar
site_author: Michael Lesser
site_url: 'https://senchar.readthedocs.io'
docs_dir: docs

# Repository
repo_name: mplesser
repo_url: https://github.com/mplesser/senchar
edit_uri: ""

theme:
  name: material
  palette:
    scheme: indigo
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/git-alt
  features:
    navigation.sections
    navigation.instant
    navigation.path
    navigation.tracking
    toc.follow
    toc.integrate
      
plugins:
- search
- autorefs
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options:
          docstring_style: google
          show_source: false
          show_root_heading: true
          show_root_full_path: true
          heading_level: 3
          parameter_headings: false
          show_root_toc_entry: false
          show_bases: true
          docstring_section_style: table

extra_css:
  - css/mkdocstrings.css

watch:
  - docs/css
  - docs/api
